### ISSUE TITLE
Create Enum Event: JFrame window not scrollable. 

### ISSUE THREAD

**Issue by sambradbury** [benthecarman/krystal-bull#41]
When creating enum events with a large number of potential outcomes the window for entering these outcomes does not become scrollable and thus is limited by the user's screen size. 
![image](https://user-images.githubusercontent.com/31943456/112765128-5449ed80-8fd1-11eb-8ca7-2316d44f71b0.png)

I believe the solution would be to make this and any other relevant JFrames generated by Kyrstal Bull into scrollable frames. I'm not familiar with Scala and do not know how to make this change myself but I would love to learn if someone can point me in the right direction. 
https://stackoverflow.com/questions/10801104/how-to-make-a-jframe-scrollable-in-java

**Comment by benthecarman** [comment]
This project is done in ScalaFX (a scala wrapper of JavaFX). I learned most of what I did from this video series: https://www.youtube.com/playlist?list=PLLMXbkbDbVt-VCR1-u4ljyHZfB0VEUw6O

I can go ahead and fix this unless you want to give it a shot

**Comment by sambradbury** [comment]
@benthecarman go ahead and fix it when you can. 
My assumption is that in CreateEnumEventDialog.scala line #9 with wildcard import should cover the addition that is needed. 
I'm just not sure if ScrollBar or ScrollPane is the right class to use. When you do fix I'll check it out and hopefully will be able to do start submitting PR's in the future.

**Comment by benthecarman** [comment]
@sambradbury #42 if you're curious
