### ISSUE TITLE
Need meaningful alerts while wrong password is entered. (RunTimeException and NullPointerException alerts poping up)

### ISSUE THREAD

**Issue by efecini** [benthecarman/krystal-bull#52]
<img width="988" alt="Ekran Resmi 2021-04-20 02 03 41" src="https://user-images.githubusercontent.com/3943422/115313887-c51d9900-a17c-11eb-825d-bd241370e391.png">
<img width="997" alt="Ekran Resmi 2021-04-20 02 03 13" src="https://user-images.githubusercontent.com/3943422/115313895-c8b12000-a17c-11eb-8d36-fd8ff3cd60ba.png">

**Comment by benthecarman** [comment]
This has been fixed, should be in the next release
